name: Auto Tag Workflow

on:
  push:
    branches:
      - main
      - beta

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Version
        run: echo "VERSION=1.1" >> $GITHUB_ENV

      - name: Fetch Tags
        run: git fetch --tags

      - name: Check Existing Tag
        id: check_tag
        run: |
          if git rev-parse ${{ env.VERSION }} >/dev/null 2>&1; then
            echo "Tag ${{ env.VERSION }} already exists locally."
            echo "TAG_EXISTS=true" >> $GITHUB_ENV  # Set environment variable
          else
            echo "Tag ${{ env.VERSION }} does not exist locally."
            echo "TAG_EXISTS=false" >> $GITHUB_ENV  # Set environment variable
          fi

      - name: Create Tag and Push
        run: |
          if [[ "${{ env.TAG_EXISTS }}" != "true" ]]; then
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git tag ${{ env.VERSION }}
            git push origin ${{ env.VERSION }}
          else
            echo "Tag ${{ env.VERSION }} already exists. Skipping tag creation."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GX_TOKEN }}
